### ISSUE TITLE
ReflectionException

### ISSUE THREAD

**Issue by ghost** [EvolSoft/ChatLogin#1]
14:34:12 [INFO] [ChatLogin] Plugin Enabled!
14:34:12 [CRITICAL] ReflectionException: "Class ChatLogin\PlayerLoginEvent does not exist" (EXCEPTION) in "/src/pocketmine/plugin/PluginManager" at line 724
14:34:12 [INFO] Disabling ChatLogin v1.0

I get this when I start up my server. I do have ServerAuth installed

**Comment by Flavius12** [comment]
Thank you for report :+1:

**Comment by Flavius12** [comment]
Fixed in v1.1 :D
